/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import util.Session;
import controller.ItemController;
import javax.swing.JOptionPane;

/**
 *
 * @author Swift
 */
public class MainFrame extends javax.swing.JFrame {
    // controller item perpustakaan
    private ItemController controller = new ItemController();
    
    // constructor mainframe
    public MainFrame() {
        initComponents();
        controller.loadTable(tblItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        cari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnPinjam = new javax.swing.JButton();
        btnHistori = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(630, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("SISTEM PERPUSTAKAAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 240, 58));

        btnCari.setText("CARI");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        getContentPane().add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 80, 70, 30));

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Jenis", "Judul", "Tahun", "Pengarang", "ISBN", "Edisi", "Penerbit"
            }
        ));
        jScrollPane1.setViewportView(tblItem);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 125, 555, 277));

        btnTambah.setText("TAMBAH");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 90, -1));

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 90, -1));

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 90, -1));
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 150, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Cari   :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 60, 30));

        btnPinjam.setText("PINJAM");
        btnPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinjamActionPerformed(evt);
            }
        });
        getContentPane().add(btnPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 430, 80, -1));

        btnHistori.setText("HISTORI");
        btnHistori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistori, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 115, -1));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 40, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        String keyword = cari.getText();
        
        // jika keyword kosong tampilkan semua data
        if (keyword.isEmpty()) {
            controller.loadTable(tblItem);
        } else {
            controller.cariTable(tblItem, keyword);
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int baris = tblItem.getSelectedRow();        
        
        // validasi pilih data
        if (baris == -1) {
            JOptionPane.showMessageDialog(this,
                    "Pilih data yang ingin dihapus!");
            return;
        }
        
        // ambil ID
        int id = Integer.parseInt(
                        tblItem.getValueAt(baris, 0).toString()
                );
        
        // konfirmasi hapus
        int konfirmasi = JOptionPane.showConfirmDialog(
                        this, "Yakin ingin menghapus data?",
                        "Konfirmasi Hapus",
                        JOptionPane.YES_NO_OPTION
                );
        // jika yes
        if (konfirmasi == JOptionPane.YES_OPTION) {
            controller.hapusItem(id);
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            controller.loadTable(tblItem);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        FormDialog dialog = new FormDialog(this, true);
        dialog.setVisible(true);
        // ambil data dari jtable
        controller.loadTable(tblItem);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int baris = tblItem.getSelectedRow();

        // validasi pilih data
        if (baris == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin diedit!");
            return;
        }

        // ambil data dari tabel
        int id = Integer.parseInt(tblItem.getValueAt(baris, 0).toString());
        
        String jenis = tblItem.getValueAt(baris, 1).toString();
        String judul = tblItem.getValueAt(baris, 2).toString();
        int tahun = Integer.parseInt(tblItem.getValueAt(baris, 3).toString());
        String pengarang = tblItem.getValueAt(baris, 4).toString();
        String isbn = tblItem.getValueAt(baris, 5).toString();
        String edisi = tblItem.getValueAt(baris, 6).toString();
        String penerbit = tblItem.getValueAt(baris, 7).toString();

        // buka form edit
        FormDialog dialog =
                new FormDialog(this, true,
                        id,
                        jenis,
                        judul,
                        tahun,
                        pengarang,
                        isbn,
                        edisi,
                        penerbit
                );

        dialog.setVisible(true);
        controller.loadTable(tblItem);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinjamActionPerformed
        int baris = tblItem.getSelectedRow();
        
        // validasi data harus dipilih
        if (baris == -1) {
            JOptionPane.showMessageDialog(this,
                    "Pilih buku terlebih dahulu!");
            return;
        }
        
        // ambil id item
        int id = Integer.parseInt(
                tblItem.getValueAt(baris, 0).toString()
        );
        
        // ambil jenis item
        String jenis = tblItem.getValueAt(baris, 1).toString();
        
        // hanya buku yang bisa dipinjam
        if (!jenis.equalsIgnoreCase("Buku")) {
            JOptionPane.showMessageDialog(this,
                    "Hanya buku yang bisa dipinjam!");
            return;
        }
        
        // ambil username user login
        String username = Session.getUsername();
        
        // proses peminjaman buku
        controller.pinjamItem(id, username);
    }//GEN-LAST:event_btnPinjamActionPerformed

    private void btnHistoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriActionPerformed
        HistoriFrame histori = new HistoriFrame();
        histori.setVisible(true);
    }//GEN-LAST:event_btnHistoriActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Session.setUsername(null);  // hapus session login
        new LoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHistori;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPinjam;
    private javax.swing.JButton btnTambah;
    private javax.swing.JTextField cari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItem;
    // End of variables declaration//GEN-END:variables
}
